name: starbelly
version: 2.0.0
description: >
  Web GUI for Starbelly crawler
authors:
  - Mark E. Haase <mehaase@gmail.com>
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angular: ^5.2.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21
  convert: ^2.1.1
  logging: ^0.11.3
  ng_fontawesome: ^5.7.2
  ng_modular_admin: ^1.0.0
  protobuf: ^0.13.4
# dependency_overrides:
#   ng_fontawesome:
#     path: ../ng_fontawesome
#   ng_modular_admin:
#     path: ../ng_modular_admin
dev_dependencies:
  build_runner: ^1.6.2
  build_test: ^0.10.2
  build_web_compilers: ^2.6.1
  sass_builder: ^2.1.2
